# Generated by Django 3.0.11 on 2021-01-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0012_file_mime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='default_alt_text_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='default alt text ru'),
        ),
        migrations.AddField(
            model_name='image',
            name='default_caption_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='default caption ru'),
        ),
    ]
