# Generated by Django 3.0.11 on 2021-01-31 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0014_migrate_translatable_fields'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='file',
            name='description',
        ),
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='author',
        ),
        migrations.RemoveField(
            model_name='image',
            name='default_alt_text',
        ),
        migrations.RemoveField(
            model_name='image',
            name='default_caption',
        ),
    ]
